config/routes.rb
Rails.application.routes.draw do
  root "departments#index"
  resources :departments do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/department.rb
class Department < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :department

  def instock_alert
    if self.instock == true
      "We have some #{self.name} in stock"
    else
      "Sorry #{self.name} are out of stock"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_dep, only: [:show, :update, :edit, :destroy]
  def index
    @deps = Department.all
  end

  def show
  end

  def new
    @dep = Department.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def update
    @dep = Department.new(dep_params)
    if @dep.save
      redirect_to departments_path
    else
      render partial: "form"
    end
  end
  def create
    @dep = Department.new(dep_params)
    if @dep.save
      redirect_to departments_path
    else 
      render partial: "form"
    end
  end

  def destroy
    @dep.destroy
    redirect_to departments_path
  end



  private
  def set_dep
    @dep = Department.find(params[:id])
  end
  def dep_params
    params.require(:department).permit(:name)
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_dep
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  def index
    @items = @dep.items
  end

  def show
  end

  def new
    @item = @dep.items.new
    render partial: "form"
  end

  def edit
    render partial: "form"
  end

  def create
    @item = @dep.items.new(item_params)
    if @item.save
    redirect_to department_item_path(@dep, @item)
    else
    render partial: "form"
    end

    def update
      if @item.update(item_params)
        redirect_to department_item_path(@dep, @item)
      else
        render partial: "form"
      end
    end

    def destroy
      @item.destroy
      redirect_to department_item_path(@dep)
    end


  end
  private

  def set_dep
    @dep = Department.find(params[:department_id])
  end

  def set_item
    @item = Item.find(params[:id])
  end
  def item_params
    params.require(:item).permit(:name, :price, :instock)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/departments_helper.rb
module DepartmentsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/departments/_form.html.erb
<h1> <%=@dep.id ? 'Edit Department' : 'Create Department'%> </h1>
<hr />
<h1>
you made it here!!!
</h1>
<%=form_for @dep do |f|%>

<%=f.label :name%>
<%=f.text_field :name, required: true, autofocus: true%>
<%=f.submit%>
<%end%>

app/views/departments/index.html.erb
<h1>Welcome to Patty's Place</h1>
<hr />
<h3>Our Stores</h3>
<ul>
<%@deps.each do |dep|%>
<li>
<%= link_to dep.name, dep%>
<%end%>
</li>
</ul>
<h3>
Add to our Department
</h3>
<%=link_to "New Item", new_department_path%>

app/views/departments/show.html.erb
<h1>
Patty's Place
</h1>
<hr />

<h2 style = "text-align: center; text-decoration: none;">
<%=link_to "#{@dep.name} Inventory", department_items_path(@dep)%>
</h2>

<br />
<%=link_to 'Edit Department', edit_department_path(@dep)%>
<%=link_to 'Delete Department', @dep%>

app/views/items/_form.html.erb
<h1> <%=@item.id ? 'Edit Item' : 'Create Item'%> </h1>
<hr />
<h1>
you made it here!!!
</h1>
<%=form_for [@dep, @item] do |f|%>

<%=f.label :name%>
<%=f.text_field :name, required: true, autofocus: true%>
<%=f.label :price%>
<%=f.text_field :price, required: true, autofocus: true%>
<%=f.label :instock%>
<%=f.check_box :instock, autofocus: true%>
<%=f.submit%>
<%end%>

app/views/items/index.html.erb
<h1>
<%=@dep.name%>
</h1>

<ul>
<%@items.each do |item|%>
<li>
<%= link_to item.name, [@dep, item]%>
</li>
<%end%>
</ul>
<br/>
<%=link_to 'Add to inventory', new_department_item_path(@dep)%>
<%= link_to 'Other Department', root_path%>

app/views/items/show.html.erb
<h1>Patty's
<%=@dep.name%> 
</h1>
<h2 style= "text-align: center; color: black;">$<%= @item.price%> <%= @item.name%></h2>


<p><%=@item.instock_alert%><br /><br />
<%=link_to "Edit #{@item.name}", edit_department_item_path([@dep, @topic])%>
<%= link_to "Delete", [@dep, @topic], method: :delete%>
<%= link_to "Back to #{@dep.name}", department_items_path(@dep)%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DepApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>